export default Strings={
    Pizza:"PIZZA",
    PizzaSubText:"Cheesilious pizzas to make every day extraordinary.",
    PizzaSubText2:".......................................................................",

    TrustedPick:"Your trusted picks",
    ReOrder:"Reorder",
    OnMind:"what's on your mind?",
    QuickPick:"Quick picks for you",
    ResToExplore:"1113 restuarants to explore",

    Home:"Home",
    Address:"39,1st cross Street,tidel park,chennai...",

    SearchText:"Search, Order, Enjoy, Repeat!",

    TryNew1:"Craving for something",
    New:"New?",
    TryWhatToEat:"Try WhatToEat",
    GetItQuickly:"Get it quickly",
    PureVeg:"pure veg",
    PopularBrands:"popular Brands",
    SeeMoreRestuarants:"See More Restuarants",
    Filter:"Filter",
    SortBy:"Sort by ",
    FastDelivery:"Fast Delivery",
    Cuisines:"Cuisines",
    NewOnSwiggy:"New on Swiggy",
    PureVeg:"Pure Veg",
    Rate:"Rs.300-Rs.600",
    Less:"Less than Rs.300",

    SavedAdd:"S A V E D   A D D R E S S E S",
    ViewMore:"View More ",
    RecentSearches:"R E C E N T   S E A R C H E S",
    LocationAdd:"Enter your area or apartment name",
    LocationSearch:"Try JP Nagar, Siri Gardenia, etc.",
    CurrentLoc:"Use my current location",
    TidelPark:"Tidel Park",
    RecentText1:"No 4 Rajiv Gandhi Salai, Taramani, Chennai",

    RetrivingLocation:"Retriving Location...",
    Recommended:"Recommended (19)",
    Zaitoon:"Zaitoon",
    Rating:"4.2(10K+ ratings)",
    ForTwo:"₹500 for two",
    Briyani:"Briyani, Juices",
    Outlet:"Outlet   ",
    Tambaram:"Tambaram",
    Mins:"51 mins",
    Delivery:"Delivery to Home",

    Far:" Far (4.3 kms)",
    Additional:"| Additional delivery fee will apply",
    FreeDelivery:"Free Delivery",
    Menu:"M E N U",
    SearchFor:"                                Search for dishes",

    guiltfree:"guiltfree",
    Bestseller:"Bestseller ",
    Veg:"Veg",
    NonVeg:"Non Veg",
}